#######################################################
# 
# ManagerControl.py
# Python implementation of the Class ManagerControl
# Generated by Enterprise Architect
# Created on:      16-5��-2019 12:06:10
# Original author: ����
# 
#######################################################
from Models.Statement import Statement
from Controllers.User import User
from Controllers.Login import Login

class ManagerControl(User):
    m_Login = Login()
    def __init__(self):
        pass

    def enter_contract(self):
        pass

    def enter_fee(self):
        pass

    def login(self,name,password,identity):
        super().login(name,password,identity)

    def registration(self):
        pass

    def remind_arrearage(self):
        pass

    def remind_expiration_con(self):
        pass