#######################################################
# 
# Registration.py
# Python implementation of the Class Registration
# Generated by Enterprise Architect
# Created on:      16-5��-2019 12:06:10
# Original author: ����
# 
#######################################################
from Controllers.User import User

class Registration:
    m_User= User()

    def judge(self):
        pass

    def putin(self):
        pass

    def run(self):
        pass