#######################################################
# 
# CEOControl.py
# Python implementation of the Class CEOControl
# Generated by Enterprise Architect
# Created on:      16-5��-2019 12:06:10
# Original author: ����
# 
#######################################################
from Models.Statement import Statement
from Controllers.User import User
from Controllers.Login import Login

class CEOControl(User):
    m_Statement= Statement()
    m_Login = Login()

    def __init__(self):
        self.__identity = 'ceo'

    def check_all_information(self):
        pass

    def get_all_contracts(self):
        return self.m_Statement.contracts

    def get_all_receipts(self):
        return self.m_Statement.receipts

    def get_all_receivable(self):
        return self.m_Statement.receivable

    def confirm_contract(self):
        pass

    def login(self,name,password,identity):
        super().login(name,password,identity)

    def registration(self):
        pass

    def remind_arrearage(self):
        pass

    def remind_expiration_con(self):
        pass

    def sign_contract(self):
        pass

if __name__ == '__main__':
    ceo = CEOControl()
    ceo.login('as',12,'ceo')