#######################################################
# 
# ProprietorControl.py
# Python implementation of the Class ProprietorControl
# Generated by Enterprise Architect
# Created on:      16-5��-2019 12:06:10
# Original author: ����
# 
#######################################################
from Models.Shop import Shop
from Controllers.User import User
from Controllers.Login import Login

class ProprietorControl(User):
    m_Login = Login()
    def __init__(self):
        pass

    def apply_to_enter(self):
        pass

    def apply_to_sublet(self):
        pass

    def login(self,name,password,identity):
        super().login(name,password,identity)

    def pay(self):
        pass

    def registration(self):
        pass

    def sign_contract(self):
        pass

    def view_status(self):
        pass