# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ManagerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ManagerWindow(object):
    def setupUi(self, ManagerWindow):
        ManagerWindow.setObjectName("ManagerWindow")
        ManagerWindow.resize(865, 599)
        self.frame = QtWidgets.QFrame(ManagerWindow)
        self.frame.setGeometry(QtCore.QRect(0, 0, 841, 581))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widgetMenu = QtWidgets.QWidget(self.frame)
        self.widgetMenu.setGeometry(QtCore.QRect(160, 10, 650, 30))
        self.widgetMenu.setObjectName("widgetMenu")
        self.btnMenu_Close = QtWidgets.QPushButton(self.widgetMenu)
        self.btnMenu_Close.setGeometry(QtCore.QRect(620, 0, 30, 30))
        self.btnMenu_Close.setObjectName("btnMenu_Close")
        self.btnMenu_Max = QtWidgets.QPushButton(self.widgetMenu)
        self.btnMenu_Max.setGeometry(QtCore.QRect(590, 0, 30, 30))
        self.btnMenu_Max.setObjectName("btnMenu_Max")
        self.btnMenu_Min = QtWidgets.QPushButton(self.widgetMenu)
        self.btnMenu_Min.setGeometry(QtCore.QRect(560, 0, 30, 30))
        self.btnMenu_Min.setObjectName("btnMenu_Min")
        self.widgetLeft = QtWidgets.QWidget(self.frame)
        self.widgetLeft.setGeometry(QtCore.QRect(10, 10, 150, 481))
        self.widgetLeft.setObjectName("widgetLeft")
        self.widgetBtn = QtWidgets.QWidget(self.widgetLeft)
        self.widgetBtn.setGeometry(QtCore.QRect(0, 30, 150, 450))
        self.widgetBtn.setStyleSheet("QToolButton\n"
"{    \n"
"color:rgb(255, 255, 255);\n"
"background:#66A5ad;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"QWidget\n"
"{\n"
"background:rgb(67, 66, 58)\n"
"}\n"
"\n"
"QToolButton:hover\n"
"{\n"
"    color:rgb(255, 234, 246);\n"
"    borderr-radius:10px;\n"
"    background:#07575B;\n"
"}\n"
"\n"
"")
        self.widgetBtn.setObjectName("widgetBtn")

        self.btnMyShop = QtWidgets.QToolButton(self.widgetBtn)
        self.btnMyShop.setGeometry(QtCore.QRect(0, 50, 150, 50))
        self.btnMyShop.setObjectName("btnMyShop")
        self.btnAllShop = QtWidgets.QToolButton(self.widgetBtn)
        self.btnAllShop.setGeometry(QtCore.QRect(0, 0, 150, 50))
        self.btnAllShop.setStyleSheet("")
        self.btnAllShop.setObjectName("btnAllShop")
        self.btnInf = QtWidgets.QToolButton(self.widgetBtn)
        self.btnInf.setGeometry(QtCore.QRect(0, 100, 150, 50))
        self.btnInf.setObjectName("btnInf")
        self.btnContract = QtWidgets.QToolButton(self.widgetBtn)
        self.btnContract.setGeometry(QtCore.QRect(0, 150, 150, 50))
        self.btnContract.setObjectName("btnContract")
        self.btnSublease = QtWidgets.QToolButton(self.widgetBtn)
        self.btnSublease.setGeometry(QtCore.QRect(0, 200, 150, 50))
        self.btnSublease.setObjectName("btnSublease")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(161, 40, 650, 450))
        self.stackedWidget.setStyleSheet("QWidget{\n"
"background:rgb(167, 167, 167);\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.AllShop = QtWidgets.QWidget()
        self.AllShop.setObjectName("AllShop")
        self.allShop = QtWidgets.QLabel(self.AllShop)
        self.allShop.setGeometry(QtCore.QRect(0, 0, 54, 41))
        self.allShop.setObjectName("allShop")
        self.stackedWidget.addWidget(self.AllShop)
        self.MyShop = QtWidgets.QWidget()
        self.MyShop.setObjectName("MyShop")
        self.myShop = QtWidgets.QLabel(self.MyShop)
        self.myShop.setGeometry(QtCore.QRect(10, 10, 101, 31))
        self.myShop.setStyleSheet("font-size:22px")
        self.myShop.setObjectName("myShop")
        self.Receipt = QtWidgets.QWidget(self.MyShop)
        self.Receipt.setGeometry(QtCore.QRect(0, 100, 521, 350))
        self.Receipt.setStyleSheet("font-size:20px")
        self.Receipt.setObjectName("Receipt")
        self.electricChargeLabel = QtWidgets.QLabel(self.Receipt)
        self.electricChargeLabel.setGeometry(QtCore.QRect(60, 40, 90, 30))
        self.electricChargeLabel.setObjectName("electricChargeLabel")
        self.guaranteeChargeLabel = QtWidgets.QLabel(self.Receipt)
        self.guaranteeChargeLabel.setGeometry(QtCore.QRect(60, 80, 80, 30))
        self.guaranteeChargeLabel.setObjectName("guaranteeChargeLabel")
        self.propertyFeeChargeLabel = QtWidgets.QLabel(self.Receipt)
        self.propertyFeeChargeLabel.setGeometry(QtCore.QRect(60, 120, 110, 30))
        self.propertyFeeChargeLabel.setObjectName("propertyFeeChargeLabel")
        self.waterChargeLabel = QtWidgets.QLabel(self.Receipt)
        self.waterChargeLabel.setGeometry(QtCore.QRect(60, 160, 100, 30))
        self.waterChargeLabel.setObjectName("waterChargeLabel")
        self.guaranteeCharge = QtWidgets.QLabel(self.Receipt)
        self.guaranteeCharge.setGeometry(QtCore.QRect(180, 80, 80, 30))
        self.guaranteeCharge.setObjectName("guaranteeCharge")
        self.electricCharge = QtWidgets.QLabel(self.Receipt)
        self.electricCharge.setGeometry(QtCore.QRect(180, 40, 80, 30))
        self.electricCharge.setObjectName("electricCharge")
        self.propertyFeeCharge = QtWidgets.QLabel(self.Receipt)
        self.propertyFeeCharge.setGeometry(QtCore.QRect(180, 120, 80, 30))
        self.propertyFeeCharge.setObjectName("propertyFeeCharge")
        self.waterCharge = QtWidgets.QLabel(self.Receipt)
        self.waterCharge.setGeometry(QtCore.QRect(180, 160, 81, 30))
        self.waterCharge.setObjectName("waterCharge")
        self.PayImmediately = QtWidgets.QPushButton(self.Receipt)
        self.PayImmediately.setGeometry(QtCore.QRect(300, 220, 80, 30))
        self.PayImmediately.setStyleSheet("font-size:15px;\n"
"background:transparent;\n"
"")
        self.PayImmediately.setObjectName("PayImmediately")
        self.ReceiptCharge = QtWidgets.QPushButton(self.MyShop)
        self.ReceiptCharge.setGeometry(QtCore.QRect(0, 70, 80, 30))
        self.ReceiptCharge.setStyleSheet("\n"
"background:transparent;\n"
"")
        self.ReceiptCharge.setObjectName("ReceiptCharge")
        self.ReceivableCharge = QtWidgets.QPushButton(self.MyShop)
        self.ReceivableCharge.setGeometry(QtCore.QRect(80, 70, 80, 30))
        self.ReceivableCharge.setStyleSheet("\n"
"background:transparent;\n"
"")
        self.ReceivableCharge.setObjectName("ReceivableCharge")
        self.Receivable = QtWidgets.QWidget(self.MyShop)
        self.Receivable.setGeometry(QtCore.QRect(60, 100, 561, 351))
        self.Receivable.setStyleSheet("font-size:20px")
        self.Receivable.setObjectName("Receivable")
        self.guaranteeReceivable = QtWidgets.QLabel(self.Receivable)
        self.guaranteeReceivable.setGeometry(QtCore.QRect(220, 190, 80, 30))
        self.guaranteeReceivable.setObjectName("guaranteeReceivable")
        self.guaranteeChargeLabel_3 = QtWidgets.QLabel(self.Receivable)
        self.guaranteeChargeLabel_3.setGeometry(QtCore.QRect(100, 190, 80, 30))
        self.guaranteeChargeLabel_3.setObjectName("guaranteeChargeLabel_3")
        self.electricChargeLabel_3 = QtWidgets.QLabel(self.Receivable)
        self.electricChargeLabel_3.setGeometry(QtCore.QRect(100, 70, 90, 30))
        self.electricChargeLabel_3.setObjectName("electricChargeLabel_3")
        self.waterReceivable = QtWidgets.QLabel(self.Receivable)
        self.waterReceivable.setGeometry(QtCore.QRect(220, 110, 81, 30))
        self.waterReceivable.setObjectName("waterReceivable")
        self.propertyFeeReceivable = QtWidgets.QLabel(self.Receivable)
        self.propertyFeeReceivable.setGeometry(QtCore.QRect(220, 150, 80, 30))
        self.propertyFeeReceivable.setObjectName("propertyFeeReceivable")
        self.waterChargeLabel_3 = QtWidgets.QLabel(self.Receivable)
        self.waterChargeLabel_3.setGeometry(QtCore.QRect(100, 110, 100, 30))
        self.waterChargeLabel_3.setObjectName("waterChargeLabel_3")
        self.propertyFeeChargeLabel_3 = QtWidgets.QLabel(self.Receivable)
        self.propertyFeeChargeLabel_3.setGeometry(QtCore.QRect(100, 150, 110, 30))
        self.propertyFeeChargeLabel_3.setObjectName("propertyFeeChargeLabel_3")
        self.electricReceivable = QtWidgets.QLabel(self.Receivable)
        self.electricReceivable.setGeometry(QtCore.QRect(220, 70, 80, 30))
        self.electricReceivable.setObjectName("electricReceivable")
        self.myShop.raise_()
        self.ReceiptCharge.raise_()
        self.ReceivableCharge.raise_()
        self.Receivable.raise_()
        self.Receipt.raise_()
        self.stackedWidget.addWidget(self.MyShop)
        self.MyInformation = QtWidgets.QWidget()
        self.MyInformation.setObjectName("MyInformation")
        self.myInformation = QtWidgets.QLabel(self.MyInformation)
        self.myInformation.setGeometry(QtCore.QRect(20, 20, 54, 12))
        self.myInformation.setObjectName("myInformation")
        self.stackedWidget.addWidget(self.MyInformation)
        self.MyContract = QtWidgets.QWidget()
        self.MyContract.setObjectName("MyContract")
        self.myContract = QtWidgets.QLabel(self.MyContract)
        self.myContract.setGeometry(QtCore.QRect(20, 20, 54, 12))
        self.myContract.setObjectName("myContract")
        self.stackedWidget.addWidget(self.MyContract)
        self.ApplyForSublease = QtWidgets.QWidget()
        self.ApplyForSublease.setObjectName("ApplyForSublease")
        self.applyForSublease = QtWidgets.QLabel(self.ApplyForSublease)
        self.applyForSublease.setGeometry(QtCore.QRect(30, 20, 54, 12))
        self.applyForSublease.setObjectName("applyForSublease")
        self.stackedWidget.addWidget(self.ApplyForSublease)

        self.retranslateUi(ManagerWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ManagerWindow)

    def retranslateUi(self, ManagerWindow):
        _translate = QtCore.QCoreApplication.translate
        ManagerWindow.setWindowTitle(_translate("ManagerWindow", "Form"))
        self.btnMenu_Close.setText(_translate("ManagerWindow", "×"))
        self.btnMenu_Max.setText(_translate("ManagerWindow", "×"))
        self.btnMenu_Min.setText(_translate("ManagerWindow", "×"))
        self.btnMyShop.setText(_translate("ManagerWindow", "我的店铺"))
        self.btnAllShop.setText(_translate("ManagerWindow", "全部店铺"))
        self.btnInf.setText(_translate("ManagerWindow", "我的信息"))
        self.btnContract.setText(_translate("ManagerWindow", "我的合同"))
        self.btnSublease.setText(_translate("ManagerWindow", "申请转租"))
        self.allShop.setText(_translate("ManagerWindow", "全部店铺"))
        self.myShop.setText(_translate("ManagerWindow", "我的店铺"))
        self.electricChargeLabel.setText(_translate("ManagerWindow", "应缴电费："))
        self.guaranteeChargeLabel.setText(_translate("ManagerWindow", "保证金："))
        self.propertyFeeChargeLabel.setText(_translate("ManagerWindow", "应缴物业费："))
        self.waterChargeLabel.setText(_translate("ManagerWindow", "应缴水费："))
        self.guaranteeCharge.setText(_translate("ManagerWindow", "TextLabel"))
        self.electricCharge.setText(_translate("ManagerWindow", "TextLabel"))
        self.propertyFeeCharge.setText(_translate("ManagerWindow", "TextLabel"))
        self.waterCharge.setText(_translate("ManagerWindow", "TextLabel"))
        self.PayImmediately.setText(_translate("ManagerWindow", "立即缴费"))
        self.ReceiptCharge.setText(_translate("ManagerWindow", "我的账单"))
        self.ReceivableCharge.setText(_translate("ManagerWindow", "已缴费用"))
        self.guaranteeReceivable.setText(_translate("ManagerWindow", "TextLabel"))
        self.guaranteeChargeLabel_3.setText(_translate("ManagerWindow", "已缴保证金："))
        self.electricChargeLabel_3.setText(_translate("ManagerWindow", "电费余额："))
        self.waterReceivable.setText(_translate("ManagerWindow", "TextLabel"))
        self.propertyFeeReceivable.setText(_translate("ManagerWindow", "TextLabel"))
        self.waterChargeLabel_3.setText(_translate("ManagerWindow", "水费余额："))
        self.propertyFeeChargeLabel_3.setText(_translate("ManagerWindow", "已缴物业费："))
        self.electricReceivable.setText(_translate("ManagerWindow", "TextLabel"))
        self.myInformation.setText(_translate("ManagerWindow", "我的信息"))
        self.myContract.setText(_translate("ManagerWindow", "我的合同"))
        self.applyForSublease.setText(_translate("ManagerWindow", "申请转租"))

